############# English navigation ##############

# main menu
[[main]]
name = "The App"
url = "/"
weight = 1

[[main]]
name = "Conquerors"
url = "/authors"
weight = 4

[[main]]
name = "Help center"
url = "/blog"
weight = 5

[[main]]
name = "Contact"
url = "/contact"
weight = 6

# footer menu
[[footer]]
name = "The App"
url = ""
weight = 1

    [[footer]]
     parent = "The App"
     name = "Changelog"
     url = "/changelog"

    [[footer]]
     parent = "The App"
     name = "Roadmap"
     url = "/roadmap"

    [[footer]]
     parent = "The App"
     name = "Data & Tracking"
     url = "/data-tracking"

    [[footer]]
     parent = "The App"
     name = "Running Costs"
     url = ""

[[footer]]
name = "Help Center"
url = "/blog"
weight = 2

    [[footer]]
     parent = "Help Center"
     name = "Get startet"
     url = "/blog/post-1"

    [[footer]]
     parent = "Help Center"
     name = "Space for more Quick Links"
     url = ""

[[footer]]
name = "Legal"
url = "/legal"
weight = 3

    [[footer]]
     parent = "Legal"
     name = "Privacy Policy"
     url = "/privacy-policy"

    [[footer]]
     parent = "Legal"
     name = "Cookie Policy"
     url = "/cookie-policy"

    [[footer]]
     parent = "Legal"
     name = "Terms"
     url = "/terms"